- type: rank
  id: RuMCRankSupervisor
  name: Supervisor
  prefix: Super.

- type: rank
  id: RuMCRankSeniorContractor
  name: Senior Contractor
  prefix: Sen. Con.

- type: rank
  id: RuMCRankContractor
  name: Contractor
  prefix: Con.
